name: Validate

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check format
      run: |
        yarn
        yarn run format:ci
